### ISSUE TITLE
? from regex_field import RegexField ?

### ISSUE THREAD

**Issue by netvigator** [ambitioninc/django-regex-field#25]
To make this work, I had to do this:

from regex_field.fields import RegexField

Note the ".fields" after "from regex_field".

All your examples say "from regex_field import RegexField" -- no ".fields"

Am I missing something?

**Comment by Fandekasp** [comment]
Same problem
```
In [1]: import regex_field

In [2]: regex_field
Out[2]: <module 'regex_field' from '/usr/local/lib/python3.6/site-packages/regex_field/__init__.py'>

In [3]: regex_field.default_app_config
Out[3]: 'regex_field.apps.RegexFieldConfig'

In [4]: regex_field.version
Out[4]: <module 'regex_field.version' from '/usr/local/lib/python3.6/site-packages/regex_field/version.py'>

In [5]: from regex_field import RegexField
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-d73046c716c2> in <module>()
----> 1 from regex_field import RegexField

ImportError: cannot import name 'RegexField'

In [6]: 
```

Thx for sharing the solution @netvigator .  @wesokes, @wesleykendall please update the documentation

**Comment by wesokes** [comment]
@netvigator @Fandekasp The path had to be changed many django versions ago in order to avoid importing models in the init file, but the docs were never updated. The documentation has been updated to reflect the new path. Originally it was in the init as a convenience, so the class was never actually moved, but obviously the old shortcut path is no longer valid. https://github.com/ambitioninc/django-regex-field/pull/30/files
